-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 09:58:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbSistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbSistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbSistema` DEFAULT CHARACTER SET utf8 ;
USE `dbSistema` ;

-- -----------------------------------------------------
-- Table `dbSistema`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `categoy_name` VARCHAR(50) NOT NULL,
  `category_description` VARCHAR(256) NOT NULL,
  `category_condition` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`article` (
  `idarticle` INT NOT NULL AUTO_INCREMENT,
  `idcategory` INT NOT NULL,
  `article_name` VARCHAR(50) NOT NULL,
  `article_stock` INT NOT NULL,
  `article_description` VARCHAR(512) NULL,
  `article_image` VARCHAR(50) NOT NULL,
  `article_condition` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idarticle`),
  INDEX `articulo_categoria_idx` (`idcategory` ASC) VISIBLE,
  CONSTRAINT `article_category`
    FOREIGN KEY (`idcategory`)
    REFERENCES `dbSistema`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `user_document_type` VARCHAR(20) NOT NULL,
  `user_document_number` VARCHAR(20) NOT NULL,
  `user_address` VARCHAR(70) NOT NULL,
  `user_phone` VARCHAR(20) NOT NULL,
  `user_email` VARCHAR(50) NOT NULL,
  `user_charge` VARCHAR(20) NOT NULL,
  `user_login` VARCHAR(20) NOT NULL,
  `user_password` VARCHAR(64) NOT NULL,
  `user_condition` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`user_role` (
  `iduser_role` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idrole` INT NOT NULL,
  PRIMARY KEY (`iduser_role`),
  INDEX `usuarioPermiso_usuario_idx` (`iduser` ASC) VISIBLE,
  INDEX `usuarioPermiso_permiso_idx` (`idrole` ASC) VISIBLE,
  CONSTRAINT `userRole_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `dbSistema`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userRole_role`
    FOREIGN KEY (`idrole`)
    REFERENCES `dbSistema`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`person` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `person_type` VARCHAR(20) NOT NULL,
  `person_name` VARCHAR(100) NOT NULL,
  `person_document_type` VARCHAR(20) NOT NULL,
  `person_document_number` VARCHAR(20) NOT NULL,
  `person_address` VARCHAR(70) NOT NULL,
  `person_phone` VARCHAR(20) NOT NULL,
  `person_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idperson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`entry` (
  `identry` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `entry_voucher_type` VARCHAR(20) NOT NULL,
  `entry_voucher_serie` VARCHAR(7) NOT NULL,
  `entry_voucher_number` VARCHAR(10) NOT NULL,
  `entry_datetime` DATETIME NOT NULL,
  `entry_tax` DECIMAL(4,2) NOT NULL,
  `entry_buy_total` DECIMAL(11,2) NOT NULL,
  `entry_status` TINYINT(1) NOT NULL DEFAULT 1,
  `idprovider` INT NOT NULL,
  PRIMARY KEY (`identry`),
  INDEX `ingreso_usuario_idx` (`iduser` ASC) VISIBLE,
  INDEX `ingreso_persona_idx` (`idprovider` ASC) VISIBLE,
  CONSTRAINT `entry_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `dbSistema`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entry_person`
    FOREIGN KEY (`idprovider`)
    REFERENCES `dbSistema`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`entry_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`entry_detail` (
  `identry_detail` INT NOT NULL AUTO_INCREMENT,
  `identry` INT NOT NULL,
  `idarticle` INT NOT NULL,
  `entry_detail_qty` INT NOT NULL,
  `entry_detail_buy_price` DECIMAL(11,2) NOT NULL,
  `entry_detail_sale_price` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`identry_detail`),
  INDEX `detaleIngreso_ingreso_idx` (`identry` ASC) VISIBLE,
  INDEX `detalleIngreso_articulo_idx` (`idarticle` ASC) VISIBLE,
  CONSTRAINT `entryDetail_entry`
    FOREIGN KEY (`identry`)
    REFERENCES `dbSistema`.`entry` (`identry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entryDetail_article`
    FOREIGN KEY (`idarticle`)
    REFERENCES `dbSistema`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`sale` (
  `idsale` INT NOT NULL AUTO_INCREMENT,
  `idclient` INT NOT NULL,
  `iduser` INT NOT NULL,
  `sale_vaucher_type` VARCHAR(20) NOT NULL,
  `sale_vaucher_serie` VARCHAR(7) NOT NULL,
  `sale_vaucher_number` VARCHAR(10) NOT NULL,
  `sale_datetime` DATETIME NOT NULL,
  `sale_tax` DECIMAL(4,2) NOT NULL,
  `sale_total_sale` DECIMAL(11,2) NOT NULL,
  `sale_status` VARCHAR(20) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idsale`),
  INDEX `venta_cliente_idx` (`idclient` ASC) VISIBLE,
  INDEX `venta_usuario_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `sale_person`
    FOREIGN KEY (`idclient`)
    REFERENCES `dbSistema`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sale_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `dbSistema`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`sale_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`sale_detail` (
  `idsale_detail` INT NOT NULL AUTO_INCREMENT,
  `idarticle` INT NOT NULL,
  `idsale` INT NOT NULL,
  `sale_detail_qty` INT NOT NULL,
  `sale_detail_sale_price` DECIMAL(11,2) NOT NULL,
  `sale_detail_discount` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idsale_detail`),
  INDEX `detalleVenta_articulo_idx` (`idarticle` ASC) VISIBLE,
  INDEX `detalleVenta_venta_idx` (`idsale` ASC) VISIBLE,
  CONSTRAINT `saleDetail_article`
    FOREIGN KEY (`idarticle`)
    REFERENCES `dbSistema`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sleDetail_sale`
    FOREIGN KEY (`idsale`)
    REFERENCES `dbSistema`.`sale` (`idsale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
